# Homework #0

## 1. Probability and Statistic

In [20]:
from sympy import * 
x,n,k = symbols('x n k')

#### (2) counting 

In [53]:
# a
(1/2)**10*nC(10,4)

0.205078125000000

In [52]:
# b
2*nC(13,2)*nC(4,3)*nC(4,2)/nC(52,5)

6/4165

## 2. Linear Algebra

In [3]:
import numpy as np

#### (4) SVD
- 參考教學 https://www.bilibili.com/video/av15971352/

In [68]:
M = np.mat([[4,0,5],[0,0,5]])

In [69]:
U,sigma,VT = np.linalg.svd(M)
print(U,'\n\n',sigma,'\n\n',VT)

[[-0.80770531 -0.58958641]
 [-0.58958641  0.80770531]] 

 [7.69732483 2.59830531] 

 [[-0.419733    0.         -0.90764762]
 [-0.90764762  0.          0.419733  ]
 [ 0.         -1.          0.        ]]


In [70]:
B = M * M.transpose() 
np.diag(B) #將B對角化 B=SJS(-1)
Beigvals, Beigvecs = np.linalg.eig(B)
print(Beigvals,'\n\n',Beigvals**(1/2),'\n\n',Beigvecs)

[59.2488095  6.7511905] 

 [7.69732483 2.59830531] 

 [[ 0.80770531 -0.58958641]
 [ 0.58958641  0.80770531]]


In [71]:
C = M.transpose()*M
np.diag(C)
Ceigvals, Ceigvecs = np.linalg.eig(C)
print(Ceigvals,'\n\n',Ceigvals**(1/2),'\n\n',Ceigvecs)
# Beigvecs、Ceigvecs 都是正交矩陣(col互相垂直)

[ 6.7511905 59.2488095  0.       ] 

 [2.59830531 7.69732483 0.        ] 

 [[-0.90764762 -0.419733    0.        ]
 [ 0.          0.          1.        ]
 [ 0.419733   -0.90764762  0.        ]]


In [75]:
U,sigma,VT = np.linalg.svd(M)
print(U,'\n\n',sigma,'\n\n',VT)

[[-0.80770531 -0.58958641]
 [-0.58958641  0.80770531]] 

 [7.69732483 2.59830531] 

 [[-0.419733    0.         -0.90764762]
 [-0.90764762  0.          0.419733  ]
 [ 0.         -1.          0.        ]]


In [82]:
result = np.zeros((U.shape[0],VT.shape[1]))
for i in range(0,sigma.shape[0]):
    result = result + sigma[i] * U[:,i] * VT[i,:]
    print(sigma[i],'\n\n',U[:,i],'\n\n',VT[i,:])

np.around(result)

7.697324827289891 

 [[-0.80770531]
 [-0.58958641]] 

 [[-0.419733    0.         -0.90764762]]
2.5983053136971086 

 [[-0.58958641]
 [ 0.80770531]] 

 [[-0.90764762  0.          0.419733  ]]


matrix([[ 4.,  0.,  5.],
        [-0.,  0.,  5.]])

#### (5) PD/PSD

#### (6) inner product

## 3. Calculus

#### (2) chain rule